# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Contacts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Contacts
  pod 'SnapKit', '~> 5.0.0'
  pod 'Alamofire', '~> 5.2'
  pod 'Kingfisher', '~> 5.0'
  pod 'CountryPickerView'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'IQKeyboardManagerSwift'
  target 'ContactsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ContactsUITests' do
    # Pods for testing
  end

end
